### ISSUE TITLE
Remove boostrap `Form`

### ISSUE THREAD

**Issue by DiazD** [DiazD/form-renderer#16]
### Problem
We gotta remove the ~bootstrap~ reactstrap `Form` we utilize in the form renderer

### Solution
replace it with a regular form element

**Comment by imTrovert** [comment]
Did you mean react strap?

**Comment by DiazD** [comment]
> Did you mean react strap?

Yeah reactstrap, I'll edit.

**Comment by DiazD** [comment]
closed by #22
